# Generated by Django 5.0.3 on 2024-03-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_ID', models.CharField(max_length=200)),
                ('H_name', models.CharField(max_length=200)),
                ('H_co_ordinate', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Co_ordinate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Experience', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Availabilty', models.CharField(blank=True, max_length=200, null=True)),
                ('H_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Location.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ICUVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_ICU', models.IntegerField(blank=True, null=True)),
                ('ICU_Budget', models.IntegerField(blank=True, null=True)),
                ('H_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Location.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='Co_ordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location'),
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_co_ordinate', models.CharField(blank=True, max_length=200, null=True)),
                ('A_Number', models.CharField(max_length=200)),
                ('Co_ordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('S_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('S_Budget', models.IntegerField(blank=True, null=True)),
                ('H_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Location.hospital')),
            ],
        ),
    ]
