# Generated by Django 5.0.3 on 2024-03-25 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='A_co_ordinate',
        ),
        migrations.RemoveField(
            model_name='doctorlist',
            name='D_Availabilty',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='H_co_ordinate',
        ),
        migrations.AddField(
            model_name='doctorlist',
            name='Availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='icuvacancy',
            name='H_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.hospital'),
        ),
    ]
