# Generated by Django 5.0.3 on 2024-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_remove_ambulance_a_co_ordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
