# Generated by Django 5.0.3 on 2024-04-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0009_alter_doctorlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='Co_ordinate',
            new_name='Area_name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Co_ordinate',
            new_name='Area_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Co_ordinate',
            new_name='Area_name',
        ),
    ]
