# Generated by Django 5.0.3 on 2024-05-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0011_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
