# Generated by Django 5.0.3 on 2024-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0013_alter_icuvacancy_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuvacancy',
            name='Vacancy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
