# Generated by Django 5.0.3 on 2024-05-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0014_alter_icuvacancy_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icuvacancy',
            old_name='Vacancy',
            new_name='Vacant',
        ),
    ]
