# Generated by Django 5.0.3 on 2024-05-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0015_rename_vacancy_icuvacancy_vacant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorlist',
            old_name='H_ID',
            new_name='H_Name',
        ),
        migrations.RenameField(
            model_name='icuvacancy',
            old_name='H_ID',
            new_name='H_Name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='H_ID',
            new_name='H_Name',
        ),
    ]
